### ISSUE TITLE
Winston Support in v7

### ISSUE THREAD

**Issue by MichaelFlucher** [SAP/cf-nodejs-logging-support#195]
How should the Transport for winston be created with v7?
The old way with
```typescript
import * as log from "cf-nodejs-logging-support";
log.createWinstonTransport()
```
does not work anymore, so i tried it with empty options:
```typescript
import * as log from "cf-nodejs-logging-support";
log.createWinstonTransport({})
```
This gives the following error on the BTP:
```
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR /home/vcap/app/node_modules/cf-nodejs-logging-support/build/main/lib/winston/winstonTransport.js:22
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR this.logger.logMessage(info.level, info.message);
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR ^
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR TypeError: Cannot read properties of undefined (reading 'logMessage')
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR at CfNodejsLoggingSupportLogger.log (/home/vcap/app/node_modules/cf-nodejs-logging-support/build/main/lib/winston/winstonTransport.js:22:25)
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR at CfNodejsLoggingSupportLogger._write (/home/vcap/app/node_modules/winston-transport/index.js:82:19)
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR at doWrite (/home/vcap/app/node_modules/readable-stream/lib/_stream_writable.js:409:139)
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR at writeOrBuffer (/home/vcap/app/node_modules/readable-stream/lib/_stream_writable.js:398:5)
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR at Writable.write (/home/vcap/app/node_modules/readable-stream/lib/_stream_writable.js:307:11)
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR at DerivedLogger.ondata (/home/vcap/app/node_modules/readable-stream/lib/_stream_readable.js:681:20)
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR at DerivedLogger.emit (node:events:513:28)
2023-09-25T07:53:52.786+0000 [APP/PROC/WEB/0] STDERR at addChunk (/home/vcap/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)
2023-09-25T07:53:52.787+0000 [APP/PROC/WEB/0] STDERR at readableAddChunk (/home/vcap/app/node_modules/readable-stream/lib/_stream_readable.js:280:11)
2023-09-25T07:53:52.787+0000 [APP/PROC/WEB/0] STDERR at Readable.push (/home/vcap/app/node_modules/readable-stream/lib/_stream_readable.js:241:10)
2023-09-25T07:53:52.787+0000 [APP/PROC/WEB/0] STDERR Node.js v18.16.1
2023-09-25T07:53:52.797+0000 [APP/PROC/WEB/0] STDOUT Exit status 1
2023-09-25T07:53:53.676+0000 [APP/PROC/WEB/0] STDOUT Exit status 143
```

**Comment by MichaelFlucher** [comment]
Thanks @christiand93 for the hint, I didn't even think of passing `null`.
For now I got it to work with the following lines:
```typescript
import log from "cf-nodejs-logging-support";
import * as winston from "winston";

// for the transports of winston, as there is a missing overlap reported by typescript
log.createWinstonTransport(null) as unknown as winston.transport
```

**Comment by christiand93** [comment]
The fix is merged and will be shipped with version 7.2.1.
